services:
  - type: web
    name: n8n
    env: docker
    repo: https://github.com/n8n-io/n8n.git
    dockerfilePath: /apps/n8n/docker/images/n8n-bullseye/Dockerfile
    dockerContext: /
    healthCheckPath: /healthz
    envVars:
      - key: N8N_HOST
        fromService:
          type: web
          name: n8n
          envVarKey: RENDER_EXTERNAL_URL
      - key: WEBHOOK_URL
        fromService:
          type: web
          name: n8n
          envVarKey: RENDER_EXTERNAL_URL
      - key: GENERIC_TIMEZONE
        value: Asia/Shanghai
    disks:
      - name: n8n-data
        mountPath: /home/node/.n8n
        sizeGB: 1
